---
title: "Qualification"
output: html_document
---

```{r}
source("functions_n95.R")
```

```{r}
if(Sys.info()["sysname"] == "Windows"){
  p_server <- "H:/Volckens Group/Projects/N95 Mask Certifications/Data" # Windows
}else{
  p_server <- "/Volumes/N95 Mask Certifications/Data" # OSX
}
```

# Read metadata

```{r}
meta <- read_metadata(server)
```

# Read analysis log

```{r}
analyze <- read_csv("analyze.csv", col_types = cols(.default = "c"))
```

# Files

```{r}
img_files <- list.files(p_server, 
  pattern = paste0(".*.jpg$"),
  full.names = TRUE,
  ignore.case = TRUE,
  recursive = TRUE)
```

```{r}
test_files <- list.files(p_server,
  pattern = paste0(".*_m.*.csv$"),
  ignore.case = TRUE,
  full.names = TRUE,
  recursive = TRUE) 
```

# Map tests

```{r}
analyze_f <- function(mask,
                      analysis_type = "detailed",
                      server = p_server,
                      images = img_files,
                      tests = test_files){
    render("qualification_report.Rmd",
           "pdf_document",
           params = list(id = mask, type = analysis_type, fldr = server, img = images, tst = tests),
           output_file = if_else(Sys.info()["sysname"] == "Windows",
                                paste0("H:/Volckens Group/Projects/N95 Mask Certifications/Data/qualification reports/",
                                      mask,
                                     ".pdf"),
                                paste0("/Volumes/N95 Mask Certifications/Data/qualification reports/",
                                       mask,
                                       ".pdf")))
           #output_file = paste0("reports/", mask, ".pdf")) # local
}
```

```{r}
purrr::map2(analyze$mask, analyze$type, analyze_f)
```
